### ISSUE TITLE
P2505: Add monadic inteface extensions for std::expected

### ISSUE THREAD

**Issue by wroyca** [marzer/muu#3]
**Is your feature request related to a problem? Please describe.**
[P0323](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0323r12.html) is currently missing [P2505](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2505r5.html) which is considered as a bug. (Relevant discussions: https://github.com/cplusplus/papers/issues/1161)

**Describe the solution you'd like**
Expand STL implementation to support [P2505](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2505r5.html).

**Additional context**
For example, given the following: 

```cpp
using time_expected = expected<boost::posix_time::ptime, std::string>;

time_expected from_iso_str( std::string time )
{
  try {
    ptime t  = boost::posix_time::from_iso_string( time );
    return t;
  }
  catch( std::exception& e )
  {
     return unexpected( e.what() + " str was: "s + time);
  }
}

// for use with transform
ptime next_day( boost::posix_time::ptime t )
{
   return t + boost::gregorian::days(1);
}

// for use with or_else
void print_error( std::string error )
{
   cout << error << endl;
}


//valid iso string
const std::string ts ( "20210726T000000" );
```

 Before the change we'd write this: 

```cpp
time_expected d = from_iso_str( ts );
if (d)
{
   ptime t = next_day( *d );
} 
else
{
   print_error( d.error() );
}
```

 And after, this: 
```cpp
// chain a series of functions until there's an error
auto d = from_iso_str ( ts )
               .or_else( print_error )
               .transform( next_day ) ;
```

**Comment by marzer** [comment]
Er... what? Have you got the right repo? `muu` doesn't have a `std::expected` implementation O_O

**Comment by marzer** [comment]
Unless you're suggesting I add one, in which case, let me introduce you to: [tl::expected](https://github.com/TartanLlama/expected) 😄

**Comment by wroyca** [comment]
> Er... what? Have you got the right repo? `muu` doesn't have `std::expected` implementation O_O

Oops, I was in a hurry and just noticed that the original text was deleted! This is a feature request to add muu::expected following the default implementation ( so no deviation like tl ) but with P2505 adapted :)

**Comment by marzer** [comment]
> so no deviation like tl 

This one is cited in the paper as being a 'standard' implementation of both proposals, might be closer to what you want: https://github.com/RishabhRD/expected

**Comment by wroyca** [comment]
> > so no deviation like tl
> 
> This one is cited in the paper as being a 'standard' implementation of both proposals, might be closer to what you want: https://github.com/RishabhRD/expected

That's really neat! Sound like a good replacement

**Comment by wroyca** [comment]
Closing in favor of rd, reopen if necessary ( :
